#+TITLE: 2D Arrays
#+PROPERTY: header-args

As we have learned previously, an array is a group of data consisting of the same type. This means that we can have an array of primitive data types (such as integers):
#+BEGIN_EXAMPLE
[1, 2, 3, 4, 5]
#+END_EXAMPLE

We can even have an array of Objects. For example, the following example shows an array of String Objects:
#+BEGIN_EXAMPLE
["hello", "world", "how", "are", "you"]
#+END_EXAMPLE

In Java, arrays are considered Objects; therefore, we can also have an array of arrays:
#+BEGIN_EXAMPLE
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
#+END_EXAMPLE

These are called 2D arrays since we can logically view them as a two-dimensional matrix of values containing both rows and columns.
| 1 | 2 | 3 |
| 4 | 5 | 6 |
| 7 | 8 | 9 |

Additionally, we can have 2D arrays which are not rectangular in shape. These are called jagged arrays:
#+BEGIN_EXAMPLE
[['a', 'b', 'c', 'd'], ['e', 'f'], ['g', 'h', 'i', 'j'], ['k']]
#+END_EXAMPLE
+---+---+---+---+
| a | b | c | d |
+---+---+---+---+
|   e   |   f   |
+---+---+---+---+
| g | h | i | j |
+---+---+---+---+
|       k       |
+---+---+---+---+

We won’t be covering jagged arrays in this lesson, but be aware that 2D arrays don’t always have to have the same number of subarrays in each array. This would cause the shape of the 2D array to not be rectangular.

Why use 2D arrays?
- It is useful to use 2D arrays for situations where you need to store and organize data by rows and columns. For example, exporting data to be used in a spreadsheet.
- You can condense multiple arrays down to a single variable using 2D arrays. For example, if you have 10 students who each have 10 different quiz grades, you can represent the overall class quiz grades as a 10x10 2D array by having each row represent a student and each column represent one of the quizzes they have taken.
- 2D arrays can be used to map out data. For example, if you want to create a game of tic-tac-toe, you can represent the game state by using a 3x3 2D array.

There are many other ways to use 2D arrays depending on the application. The only downside is that once initialized, no new rows or columns can be added or removed without copying the data to a newly initialized 2D array. This is because the length of arrays in Java are immutable (unable to be changed after creation).

* Declaration, Initialization, and Assignment
  When declaring 2D arrays, the format is similar to normal, one-dimensional arrays, except that you include an extra set of brackets after the data type. In this example, int represents the data type, the first set of brackets [] represent an array, and the second set of brackets [] represent that we are declaring an array of arrays.
  #+BEGIN_SRC java
  int[][] intTwoDArray;
  #+END_SRC

  You can think of this as creating an array ([]) of int arrays (int[]). So we end up with int[][].

  Now that we’ve declared a 2D array, let’s look at how to initialize it with starting values. When initializing arrays, we define their size. Initializing a 2D array is different because, instead of only including the number of elements in the array, you also indicate how many elements are going to be in the sub-arrays. This can also be thought of as the number of rows and columns in the 2D matrix.
  #+BEGIN_SRC java
  int[][] intArray1;
  intArray1 = new int[row][column];
  Here is an example of initializing an empty 2D array with 3 rows and 5 columns.

  int[][] intArray2;
  intArray2 = new int[3][5];
  #+END_SRC

  This results in a matrix which looks like this:
  | 0 | 0 | 0 | 0 | 0 |
  | 0 | 0 | 0 | 0 | 0 |
  | 0 | 0 | 0 | 0 | 0 |

  If you already know what values are going to be in the 2D array, you can initialize it and write all of the values into it at once. We can accomplish this through initializer lists
  - In Java, initializer lists are a way of initializing arrays and assigning values to them at the same time
  - We can use this for 2D arrays as well by creating an initializer list of initializer lists

  An example of an initializer list for a regular array would be:
  #+BEGIN_SRC java
  char[] charArray = {'a', 'b', 'c', 'd'};
  #+END_SRC

  Similar to how a regular initializer list defines the size and values of the array, nested initializer lists will define the number of rows, columns, and the values for a 2D array.

  There are three situations in which we can use initializer lists for 2D arrays:

  1. In the case where the variable has not yet been declared, we can provide an abbreviated form since Java will infer the data type of the values in the initializer lists:
     #+BEGIN_SRC java
     double[][] doubleValues = {{1.5, 2.6, 3.7}, {7.5, 6.4, 5.3}, {9.8,  8.7, 7.6}, {3.6, 5.7, 7.8}};
     #+END_SRC
  2. If the variable has already been declared, you can initialize it by creating a new 2D array object with the initializer list values:
     #+BEGIN_SRC java
     String[][] stringValues;
     stringValues = new String[][] {{"working", "with"}, {"2D", "arrays"}, {"is", "fun"}};
     #+END_SRC
  3. The previous method also applies to assigning a new 2D array to an existing 2D array stored in a variable.

  In the next exercise, we’ll look at how to assign values of individual elements.

* Accessing Elements in a 2D Array
  Let’s first review how to access elements in regular arrays.

  For a normal array, all we need to provide is an index (starting at 0) which represents the position of the element we want to access. Let’s look at an example!

  Given an array of five Strings:
  #+BEGIN_SRC java
  String[] words = {"cat", "dog", "apple", "bear", "eagle"};
  #+END_SRC

  We can access the first element using index 0, the last element using the length of the array minus one (in this case, 4), and any of the elements in between. We provide the index of the element we want to access inside a set of brackets. Let’s see those examples in code:
  #+BEGIN_SRC java
  // Store the first element from the String array
  String firstWord = words[0]; 

  // Store the last element of the String array
  String lastWord = words[words.length-1];

  // Store an element from a different position in the array
  String middleWord = words[2];
  #+END_SRC

  Now for 2D arrays, the syntax is slightly different. This is because instead of only providing a single index, we provide two indices. Take a look at this example:
  #+BEGIN_SRC java
  // Given a 2D array of integer data
  int[][] data = {{2,4,6}, {8,10,12}, {14,16,18}};

  // Access and store a desired element 
  int stored = data[0][2];
  #+END_SRC

  There are two ways of thinking when accessing a specific element in a 2D array:
  - The first way of thinking is that the first value represents a row and the second value represents a column in the matrix
  - The second way of thinking is that the first value represents which subarray to access from the main array and the second value represents which element of the subarray is accessed

  The above example of the 2D array called data can be visualized like so. The indices are labeled outside of the matrix:
  | index |  0 |  1 |  2 |
  |-------+----+----+----|
  |     0 |  2 |  4 |  6 |
  |     1 |  8 | 10 | 12 |
  |     2 | 14 | 16 | 18 |

  Using this knowledge, we now know that the result of int stored = data[0][2]; would store the integer 6. This is because the value 6 is located on the first row (index 0) and the third column (index 2). Here is a template which can be used for accessing elements in 2D arrays:
  #+BEGIN_SRC java
  datatype variableName = existing2DArray[row][column];
  #+END_SRC

  Here is another way to visualize the indexing system for our example integer array seen above. We can see what row and column values are used to access the element at each position.
  #+BEGIN_EXAMPLE
  [data[0][0], data[0][1], data[0][2]]
  [data[1][0], data[1][1], data[1][2]]
  [data[2][0], data[2][1], data[2][2]]
  #+END_EXAMPLE

  When accessing these elements, if either the row or column value is out of bounds, then an ArrayIndexOutOfBoundsException will be thrown by the application.

* Modifying Elements in a 2D Array
  Now let’s review how to modify elements in a normal array.

  For a one dimensional array, you provide the index of the element which you want to modify within a set of brackets next to the variable name and set it equal to an acceptable value:
  #+BEGIN_SRC java
  storedArray[5] = 10;
  #+END_SRC

  For 2D arrays, the format is similar, but we will provide the outer array index in the first set of brackets and the subarray index in the second set of brackets. We can also think of it as providing the row in the first set of brackets and the column index in the second set of brackets if we were to visualize the 2D array as a rectangular matrix:
  #+BEGIN_SRC java
  twoDArray[1][3] = 150;
  #+END_SRC

  To assign a new value to a certain element, make sure that the new value you are using is either of the same type or is castable to the type already in the 2D array.

  Let’s say we wanted to replace four values from a new 2D array called intTwoD. Look at this example code to see how to pick individual elements and assign new values to them.
  #+BEGIN_SRC java
  int[][] intTwoD = new int[4][3];

  intTwoD[3][2] = 16;
  intTwoD[0][0] = 4;
  intTwoD[2][1] = 12;
  intTwoD[1][1] = 8;
  #+END_SRC

  Here is a before and after image showing when the 2D array was first initialized compared to when the four elements were accessed and modified.
  | before  | after     |
  |---------+-----------|
  | 0, 0, 0 | 4, 0,  0  |
  | 0, 0, 0 | 0, 8,  0  |
  | 0, 0, 0 | 0, 12, 0  |
  | 0, 0, 0 | 0, 0,  16 |

* Review of Nested Loops
  We’re about to look at how we can use loops to make our lives easier when working with 2D arrays. But before we do that, let’s take a moment to refresh ourselves on how nested loops work.

  Nested loops consist of two or more loops placed within each other. We will be looking at one loop nested within another for 2D traversal.

  The way it works is that, for every iteration of the outer loop, the inner loop finishes all of its iterations.

  Here is an example using for loops:
  #+BEGIN_SRC java
  for(int outer = 0; outer < 3; outer++){
      System.out.println("The outer index is: " + outer);
      for(int inner = 0; inner < 4; inner++){
          System.out.println("\tThe inner index is: " + inner);
      }
  }
  #+END_SRC

  The output of the above nested loops looks like so:
  #+BEGIN_EXAMPLE
  The outer index is: 0
      The inner index is: 0
      The inner index is: 1
      The inner index is: 2
      The inner index is: 3
  The outer index is: 1
      The inner index is: 0
      The inner index is: 1
      The inner index is: 2
      The inner index is: 3
  The outer index is: 2
      The inner index is: 0
      The inner index is: 1
      The inner index is: 2
      The inner index is: 3
  #+END_EXAMPLE

  From this example we can see how every time the outer loop iterates one time, the inner loop iterates fully.

  This is an important concept for 2D array traversal, because for every row in a two dimensional matrix, we want to iterate through every column. We will look more at this in the next exercise.

  Nested loops can consist of any type of loop and with any combination of loops. Let’s take a look at a few more interesting examples.

  Here is an example of nested while loops:
  #+BEGIN_SRC java
  int outerCounter = 0;
  int innerCounter = 0; 
  while(outerCounter<5){
      outerCounter++;
      innerCounter = 0;
      while(innerCounter<7){
          innerCounter++;
      }
  }
  #+END_SRC

  We can even have some interesting combinations. Here is an enhanced for loop inside of a while loop:
  #+BEGIN_SRC
  int outerCounter = 0;
  int[] innerArray = {1,2,3,4,5};

  while(outerCounter<7){
      System.out.println();
      for(int number : innerArray){
          System.out.print(number * outerCounter + " ");
      }
      outerCounter++;
  }
  #+END_SRC

  The output of the above example creates a multiplication table:
  #+BEGIN_EXAMPLE
  0 0 0 0 0
  1 2 3 4 5
  2 4 6 8 10
  3 6 9 12 15
  4 8 12 16 20
  5 10 15 20 25
  6 12 18 24 30
  #+END_EXAMPLE

  This is an interesting example, because for every iteration of the while loop, we iterate through every element of an array using an enhanced for loop. This is similar to the iteration pattern we use for 2D array traversal. We will be going over that in the next exercise.

  Let’s practice using nested loops!

  You are in charge of controlling the amount of people who reserve seats for the world famous programming contest. You have two long arrays of integers which represent the contestant’s IDs for two days of the competition. The index of the array represents their seat number. You need to use nested for loops to find if a contestant tried to register for both days. Print out the ID of the contestants who tried to register twice as well as their seat numbers for both days.
