#+TITLE: Notes
#+PROPERTY: header-args

*Disclaimer*
My old notes were not designed for this website and don't link properly. These
notes can best be viewed at my [[https://github.com/maker2413/Notes/tree/master/Content/LegacyNotes][GitHub]]. In the long term these notes will be
converted into my new notes layout and this directory won't exist so this is a
temporary work around.

Just notes I made about different topics I have learned. These notes are all
written in Org mode and although that should not effect your viewing of them on
GitHub it is something to be aware of if you were to clone repo down for your
own personal use. If org mode is foreign to you you can check out my Notes I
have on org or there are converters available online to convert it to md, html,
pdf, and many other formats. Also it is important to note that any code found in
this repo has been exported from the org README files so it will be a duplicate
of what the README has, but all code in this repo is runnable and exists for
anyone to copy from.
