#+TITLE: Notes

*Deprecated*
This branch of my notes is an archive of before I restructured my notes to exist
in one directory. I put work into getting the JavaScript to support my directory
structure but ultimately got frustrated and chose to reorganize my notes repo to
a single directory for all org-roam notes. The progress I made on the JavaScript
is also included in the js directory of this branch but it is currently in a
semi broken state. This branch is kept around just in case I decide to give this
another shot at a later date.

This is my notes repo, and is a collection of guides I have put together over
topics I have learned. As of right now this repo is a quite a work in progress
but ultimately I would love for the notes here to be a collection of everything
I have learned in my career. I have recently been working on updating these
notes to a more in depth layout that will make more sense to newcomers. If you
would like to see my old notes please refer to the [[./LegacyNotes/README.org][LegacyNotes]] directory.

As of right now you can check out these guides to begin diving into my notes:
- [[id:94903e09-f03d-4b20-b2eb-1da7618282ee][Programming Languages]]
- [[id:aa1519cc-d56c-4fbf-90bd-ea284b8d706f][Tools]]

Also be sure to check out my one-off notes:
- [[id:a67cff5b-1fc5-4ed4-8daa-dede88c97261][OneOffs]]
