:PROPERTIES:
:ID:       1685a9c2-92ca-4d13-9438-c343769474de
:END:
#+title: Artificial Intelligence
#+created: [2023-04-13 Thu 22:47]
#+last_modified: [2023-04-13 Thu 22:53]
#+filetags: AI ArtificialIntelligence

Artificial intelligence (AI) is intelligence demonstrated by machines, as
opposed to intelligence of humans and other animals. Example tasks in which this
is done include speech recognition, computer vision, translation between
(natural) languages, as well as other mappings of inputs.

AI applications include advanced web search engines (e.g., Google Search),
recommendation systems (used by YouTube, Amazon, and Netflix), understanding
human speech (such as Siri and Alexa), self-driving cars (e.g., Waymo),
generative or creative tools (ChatGPT and AI art), automated decision-making,
and competing at the highest level in strategic game systems (such as chess and
Go).

Artificial intelligence was founded as an academic discipline in 1956, and in
the years since it has experienced several waves of optimism, followed by
disappointment and the loss of funding (known as an "AI winter"), followed by
new approaches, success, and renewed funding. AI research has tried and
discarded many different approaches, including simulating the brain, modeling
human problem solving, formal logic, large databases of knowledge, and imitating
animal behavior. In the first decades of the 21st century, highly mathematical
and statistical [[id:ee2e1560-29ac-4760-8387-e84ecb97dcd8][machine learning]] has dominated the field, and this technique has
proved highly successful, helping to solve many challenging problems throughout
industry and academia.

* External Links
  - https://en.wikipedia.org/wiki/Artificial_intelligence
