:PROPERTIES:
:ID:       43d75a03-0ec5-4068-b1cd-e23a0bb51cab
:END:
#+title: Common Lisp
#+created: [2022-08-19 Fri 17:44]
#+last_modified: [2022-08-21 Sun 14:06]
#+filetags: Lisp ProgrammingLanguage

Common lisp is a dialect of lisp and possible the most popular lisp in the lisp
family of languages. It can be a great language to start learning a lisp style
programming.

* Install
Being that Common Lisp is just a set of standards defined for the language there
are in fact many different implementations you can install. Due to the sheer
number of implementations, it can be quite confusing where to start. Here's a
small list of some of the them:
- [[https://www.sbcl.org/][SBCL]]
- [[https://clisp.sourceforge.io/][CLISP]]
- [[https://franz.com/products/allegro-common-lisp/][Allegro CL]]
- [[http://www.lispworks.com/][LispWorks]]
- [[https://ccl.clozure.com/][Clozure]]
- [[https://ecl.common-lisp.dev/][ECL]]
- [[https://www.cons.org/cmucl/][CMUCL]]

Of these ~sbcl~ is probably the most popular and commonly used implementation
and if you are just here to learn how to program with lisp may just be the
quickest starting point for you.

If this is your first ever experience with lisp and using a lisp repl I would
definitely recommend watching something like the following video:
https://www.youtube.com/watch?v=0DLdQ6yb7h8 to understand how to interact and
code with lisp. This video is going over a plugin for [[id:d18ed6e8-dbce-4822-9d3f-3de38246ba38][Emacs]], however the
concepts displayed of using a lisp repl are quite valuable.
