:PROPERTIES:
:ID:       309a008f-9aca-4074-951b-287f3fe27506
:END:
#+title: How This Website Is Made
#+created: [2021-11-22 Mon 22:01]
#+last_modified: [2021-11-22 Mon 23:12:04]
#+filetags: OneOff

This website is the built from my [[https://github.com/maker2413/Notes][Notes]] repo and is the best way I could come up
with to display the contents of my notes I have accumulated throughout the
years. These notes are written in [[id:be6def1e-809e-4f8e-a031-a234694a8f86][Org Mode]] and are linked together using a
package in [[id:d18ed6e8-dbce-4822-9d3f-3de38246ba38][Emacs]] called [[id:5205eaca-eac2-49fe-aeb1-e7d8d75d0a7e][Org Roam]].

* How is it made?
  With the basic description of what this website and the repo containing its
  contents out of the way let dive into how this website is being built behind
  the scenes.

  So since the content of my notes and subsequently this website are written in
  [[id:be6def1e-809e-4f8e-a031-a234694a8f86][Org Mode]] a wrote a script in [[id:960b6e04-6c5a-413f-b0ca-ed89e06c3542][ELisp]] called [[https://github.com/maker2413/Notes/blob/master/publish.el][publish.el]] that configures settings
  for the ox-html [[id:d18ed6e8-dbce-4822-9d3f-3de38246ba38][Emacs]] package to publish org files to html files. I also
  overwrite the default publish template so I am able to insert some extra ~div~
  elements to format the website with [[id:e10c886e-46bd-4a00-bd25-5167caede214][CSS]]. Allow this script is quite complex
  and does way more than I am giving it credit for I tried to make an effort to
  document what the script is doing via comments, so if you are interested in
  the logic or if you want to use this script for a similar project you are
  working on feel free to check it out and lift anything that helps you.
