:PROPERTIES:
:ID:       b805c0d0-895d-4806-a223-6a9c99cf29fb
:END:
#+title: Jsonnet
#+created: [2022-03-13 Sun 18:03]
#+last_modified: [2022-03-13 Sun 23:04:23]
#+filetags: ProgrammingLanguage TemplatingLanguage

Jsonnet is a [[id:94903e09-f03d-4b20-b2eb-1da7618282ee][programming language]] or rather a [[id:71fa1fd6-35fd-43d6-b18c-b40c2621ca15][templating language]] for [[id:91b8e015-8303-49da-a14b-94745d3cd699][json]]
files. Though jsonnet provides and lot of power and configurability to the user
calling jsonnet a [[id:94903e09-f03d-4b20-b2eb-1da7618282ee][programming language]] like calling a calculator a
computer. Even though you can do many things in jsonnet that are similar to
other [[id:94903e09-f03d-4b20-b2eb-1da7618282ee][programming languages]] at the end of the day it is just a
[[id:71fa1fd6-35fd-43d6-b18c-b40c2621ca15][templating language]] for generating [[id:91b8e015-8303-49da-a14b-94745d3cd699][json]] documents.

* Syntax
  Any [[id:91b8e015-8303-49da-a14b-94745d3cd699][json]] document is a valid jsonnet program, so let's focus on what jsonnet
  adds to [[id:91b8e015-8303-49da-a14b-94745d3cd699][json]]. Lets start by going over some of the new syntax added by
  jsonnet:
  - Fields that happen to be valid identifiers have no quotes
  - Trailing commas at the end of arrays and objects
  - Single line and block comments
  - String literals can use both single quotes and double quotes. Single quotes
    can be used to avoid escaping double quotes from your string and double
    quotes can be used to avoid escaping single quotes from your string.
  - Text blocks, ~|||~, allow verbatim text across multiple lines.
  - You can also define single line verbatim strings with ~@~

  Now lets look at an example from [[https://jsonnet.org/learning/tutorial.html][jsonnet.org]]:
  #+begin_src jsonnet
    /* A C-style comment. */
    # A Python-style comment.
    {
      cocktails: {
        // Ingredient quantities are in fl oz.
        'Tom Collins': {
          ingredients: [
            { kind: "Farmer's Gin", qty: 1.5 },
            { kind: 'Lemon', qty: 1 },
            { kind: 'Simple Syrup', qty: 0.5 },
            { kind: 'Soda', qty: 2 },
            { kind: 'Angostura', qty: 'dash' },
          ],
          garnish: 'Maraschino Cherry',
          served: 'Tall',
          description: |||
            The Tom Collins is essentially gin and
            lemonade.  The bitters add complexity.
          |||,
        },
        Manhattan: {
          ingredients: [
            { kind: 'Rye', qty: 2.5 },
            { kind: 'Sweet Red Vermouth', qty: 1 },
            { kind: 'Angostura', qty: 'dash' },
          ],
          garnish: 'Maraschino Cherry',
          served: 'Straight Up',
          description: @'A clear \ red drink.',
        },
      },
    }
  #+end_src
