:PROPERTIES:
:ID:       c98976a7-563e-4f21-a436-f71201e24af4
:END:
#+title: Kubernetes
#+created: [2022-02-05 Sat 14:36]
#+last_modified: [2023-06-20 Tue 17:33]
#+filetags: Kubernetes Tool Linux

Kubernetes on a high level is a cluster of servers, virtual machines, or
instances that manage and orchestrate containers to provide as close to 100% up
time as possible. The word Kubernetes comes from Greek and roughly translates to
helmsman. This name was chosen because you can think of Kubernetes as the
captain of your ships (containers). Kubernetes was originally developed by a
team at [[id:d2ff01f9-43ad-4e7c-a4a3-afdac05a0609][Google]] and is built off of concepts founded from an in house container
management system called Borg. More on the history of Kubernetes can be found on
the Kubernetes website: [[https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/][here]].

This guide aims to cover everything I have learned about Kubernetes and will be
broken out into sections. Here are the sections I have so far:
- [[id:f9c8143d-15dd-478a-9490-c32288ab0471][Nodes]] :: The servers of Kubernetes.
- [[id:26364aaa-416e-46e5-ab00-fa94fe74f24c][Components]] :: The various components of Kubernetes.
- [[id:bd4386a6-191a-437a-8114-e69c3f74c407][Operators]] :: Sometimes called Controllers, these manage orchestration.
- [[id:7d58f850-096d-40c6-8b0f-64b92acba2b8][Namespaces]] :: The segregation concept of Kubernetes.
- [[id:7cbfd889-bd22-4dd3-a1e3-45ee56d93b4c][Pods]] :: Pods house containers.
- [[id:42abcbf0-bb4d-4e70-9f90-31bf190842ec][Deployments]] :: Manages [[id:bd7528e0-64d4-40f9-9295-71b820be5186][Replicasets]].
- [[id:bd7528e0-64d4-40f9-9295-71b820be5186][Replicasets]] :: Manages Pods.
