:PROPERTIES:
:ID:       e2cf1141-da2f-49f4-a836-68bd2c3c11f1
:END:
#+title: Limits
#+created: [2023-04-12 Wed 20:19]
#+last_modified: [2024-11-09 Sat 20:35]
#+filetags: Math Mathematics Calculus Limits

Limits are often taught during [[id:606c5657-c0f5-4bce-9a24-54c08274a6fa][Calculus]] in school.

The idea behind limits is to calculate what a problem will become as it
approaches a an unanswerable point. For example an instance of this would
answering something as it approaches infinity or an indeterminate
answer. Sometimes we can't work something out directly, but we can see what it
should be as we get closer to our answer.

Let's take a look at the following example:
\begin{equation}
\frac{x^2 - 1}{x - 1}
\end{equation}

For this example let's work it out for x=1:
\begin{equation}
\frac{1^2 - 1}{1 - 1} = \frac{1 - 1}{1 - 1} = \frac{0}{0}
\end{equation}

In this case 0/0 is indeterminate and can't be calculated so in a case like this
we would use limits to determine what the answer should be. We do this by see
what the ~x=1~ is as it approaches our answer incrementally:
#+ATTR_HTML: :border 2 :rules all :frame border
|       x | (x^2 - 1)/(x - 1) |
|---------+-------------------|
|     0.5 |           1.50000 |
|     0.9 |           1.90000 |
|    0.99 |           1.99000 |
|   0.999 |           1.99900 |
|  0.9999 |           1.99990 |
| 0.99999 |           1.99999 |

With this we can see that as x gets closer and closer to =1= our answer gets
close to =2=. Now this puts us in a predicament as we know that ~x=1~ is
unanswerable as it is indeterminate, but we can clearly see the answer is going
to be =2=. In this case mathematicians would say:
"The limit of ~(x^2 - 1)/(x - 1)~ as ~x~ approaches =1= is *2*."

This would be written as:
\begin{equation}
\lim_{x\to1} \frac{x^2 - 1}{x - 1} = 2
\end{equation}

To definitively say that our answer is probably =2= we should also check the
limit come from the other direction. In this example let's see what answers we
get as we descend to ~x=1~:
#+ATTR_HTML: :border 2 :rules all :frame border
|       x | (x^2 - 1)/(x - 1) |
|---------+-------------------|
|     1.5 |           2.50000 |
|     1.1 |           2.10000 |
|    1.01 |           2.01000 |
|   1.001 |           2.00100 |
|  1.0001 |           2.00010 |
| 1.00001 |           2.00001 |

So in this case we can see that our answer is also heading to =2=. This does
bring up an interesting question though. What do we do when our answer is
different coming from another direction?

To make things more simple let's just assume that we have a function: ~f(x)~ and
we are trying to find the limit at point: ~a~, but we can't answer this because
we get a different answer depending on which direction we approach ~a~. Let's
assume for this example that we get the following:
- 3.8 from the left of ~a~
- 1.3 from the right of ~a~

In this case we would use the =-= or =+= signs to define each side of our limit:
\begin{equation}
\lim_{x\to a^-} f(x) = 3.8 \hspace{1cm} \lim_{x\to a^+} f(x) = 1.3 \n
\\\lim_{x\to a} f(x) = does \ not \ exist
\end{equation}

Limits can be used even on non complex math problems, albeit a bit overkill:
\begin{equation}
\lim_{x\to 10} \frac{x}{2} = 5
\end{equation}

A big place where limits come into play is when working with infinity, as
infinity is more of a concept and than an actual number we can use in our day to
day math. Take for instance:

\begin{equation}
\frac{1}{\infty}
\end{equation}

We have no way of actually getting an answer for this, but using limits we can
see what the answer *probably* is:
#+ATTR_HTML: :border 2 :rules all :frame border
|      x |     1/x |
|--------+---------|
|      1 | 1.00000 |
|      2 | 0.50000 |
|      4 | 0.25000 |
|     10 | 0.10000 |
|    100 | 0.01000 |
|   1000 | 0.00100 |
|  10000 | 0.00010 |
| 100000 | 0.00001 |

Now we can see that as =x= gets larger, our answer tends towards =0=. We would
write this limit as:
\begin{equation}
\lim_{x\to\infty} \frac{1}{x} = 0
\end{equation}

* External Links
  - https://www.mathsisfun.com/calculus/limits.html
