:PROPERTIES:
:ID:       8f8d4797-dca7-4e7f-afcb-b12fa196d412
:END:
#+title: Linux
#+created: [2021-11-08 Mon 19:49]
#+last_modified: [2022-02-06 Sun 12:38:57]
#+filetags: OperatingSystem

Linux is an open source and free operating system and if even you have never
heard of it just by using the internet you have used it before as Linux is
commonly used on servers for its lightweight and powerful usage. Linux is also
the back bone to Android and many smart devices you may use in your day to day
life. If you are getting to any career relating to computers it is very
important to at least know a bit about running Linux as Linux runs the world.

As a good general rule of thumb if you encounter tool that you haven't used
before and you are interested how to use it most Linux tools allow you to use
either the ~-h~ flag or type ~--help~ to get helpful information about the
command. If this still doesn't help you find what you are looking for you can
use a Linux tool called [[id:97b6c627-602e-4a30-837b-75555a7eae94][man]] to view the manual page of the tool you are trying
to run. Example: ~man ls~ would give us the manual of the ~ls~ command. If you
want to learn about some of the command line tools in the Linux world please
check out some of the following guides:
- [[id:2be8b689-98da-4e62-82d9-1e0cf4b050e3][CD]] :: used to change directories
- [[id:76e95672-9ba3-4691-8149-86b65fe39533][CP]] :: used to copy files or directories
- [[id:a18196a7-adf8-4d86-af49-bb4915c366ca][LS]] :: used to list file and directories
- [[id:97b6c627-602e-4a30-837b-75555a7eae94][Man]] :: used to read manual pages for help with commands and tools
- [[id:c4903e5f-c4a9-4d0e-864b-01d7b392fdfa][Sudo]] :: allows non root users to assume the root user for the duration of
  their command

- [[id:ea6dfc82-bd00-4abe-a67d-652145adf9f5][File System]]
