:PROPERTIES:
:ID:       a262fb74-7247-415e-82e7-89a75538fa6b
:END:
#+title: Markdown
#+created: [2021-11-22 Mon 22:04]
#+last_modified: [2025-12-20 Sat 10:26]
#+filetags: Tool

Markdown is a [[id:7d97f527-f387-44c0-86c9-4dbbe0ab28e0][markup language]] and quite possibly the most common one for
documenting code. If you have ever encountered a file that ends in ~.md~ before;
that is a Markdown file. If you have ever looked at projects on [[id:0c164614-cdac-4936-aca3-a6cb340883fa][GitHub]], [[id:0856b32b-1060-4fcb-9a42-5382b11deb47][GitLab]],
or any other code hosting platform you have seen README files written in
Markdown. For this reason it can be quite vital to at least know the basics of
Markdown if you are going to be making projects that you would like to
document.

Markdown was created by John Gruber in 2004. It's meant to be an easy to read
and write syntax which converts easily to HTML (and now many other
formats). Markdown also varies in implementation from one parser to the
next. This guide will attempt to clarify with features are universal or when
they are specific to a certain parser.

* HTML Elements
  Markdown is a superset of HTML, so any HTML file is valid Markdown:
  #+begin_src markdown
    <!--This means we can use HTML elements in Markdown, such as the comment
    element, and they won't be affected by a markdown parser. However, if you
    create an HTML element in your markdown file, you cannot use markdown syntax
    within that element's contents.-->
  #+end_src

* Headings
  You can create HTML elements ~<h1>~ through ~<h6>~ easily by prepending the
  text you want to be in that element by a number of hashes (#):
  #+begin_src markdown
    # This is an <h1>
    ## This is an <h2>
    ### This is an <h3>
    #### This is an <h4>
    ##### This is an <h5>
    ###### This is an <h6>
  #+end_src

  Markdown also provides us with two alternative ways of indicating h1 and h2:
  #+begin_src markdown
    This is an h1
    =============

    This is an h2
    -------------
  #+end_src
