:PROPERTIES:
:ID:       0817633b-da6b-4889-ab18-267d6cb9ef60
:END:
#+title: TypeScript
#+created: [2021-12-05 Sun 23:57]
#+last_modified: [2021-12-06 Mon 21:53:32]
#+filetags: ProgrammingLanguage TypeScript

TypeScript is a progamming language that is based on [[id:a29e994c-1920-4ea6-8cfa-946c82e25429][JavaScript]]. In fact
TypeScript is written just like [[id:a29e994c-1920-4ea6-8cfa-946c82e25429][JavaScript]] with added syntax for types and
compiles into [[id:a29e994c-1920-4ea6-8cfa-946c82e25429][JavaScript]] with none of its own syntax left around. The type
system of TypeScript has many key features that it adds, some of these are:
- Helps to catch errors *during development*
- Uses 'type annotations' to analyze code
- TypeScript is only active *during* development. This simply means that all
  TypeScript code when compiled into [[id:a29e994c-1920-4ea6-8cfa-946c82e25429][JavaScript]] doesn't stick around and the
  machine running the [[id:a29e994c-1920-4ea6-8cfa-946c82e25429][JavaScript]] code ie: a web browser has no idea what
  TypeScript even is.
- TypeScript *doesn't* provide any performance optimization

Since TypeScript compiles to [[id:a29e994c-1920-4ea6-8cfa-946c82e25429][JavaScript]] and doesn't leave any of its own syntax
behind going forward we think of TypeScript as [[id:a29e994c-1920-4ea6-8cfa-946c82e25429][JavaScript]] with annotations
added. Although it isn't a requirement to know [[id:a29e994c-1920-4ea6-8cfa-946c82e25429][JavaScript]] before learning
TypeScript I would highly recommend you have an understanding of at least the
basics before learning TypeScript.

If you are completely new to TypeScript I would recommend viewing the following
topics in order, however if you are here for information on a specific topic
feel free to skip around:
- [[id:aa46db0b-e3fc-4c85-8ab8-66aaedf1bef2][TypeScript Type System]]
- [[id:1ecd0b78-8533-45ab-9c07-6d03f866eb9a][TypeScript Annotations]]
